"""
Meal Reminder Scheduler for NutriAI
====================================
Single source of truth: every email reads meals from the user's stored
meal_plan in MongoDB — the same plan generated by /diet/sync-meal-plan
and shown on the dashboard.

No hardcoded meals.  No GOAL_MEAL_DATABASE fallback.
"""

import logging
from datetime import datetime, timedelta

from apscheduler.schedulers.background import BackgroundScheduler
from bson import ObjectId

from ..database.db import db
from ..utils.email import send_email

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Day helpers
# ---------------------------------------------------------------------------

def _today_key() -> str:
    """Return today's day name as a lowercase string, e.g. 'saturday'."""
    return datetime.now().strftime("%A").lower()


def _tomorrow_key() -> str:
    """Return tomorrow's day name as a lowercase string, e.g. 'sunday'."""
    return (datetime.now() + timedelta(days=1)).strftime("%A").lower()


# ---------------------------------------------------------------------------
# Fetch all reminder-enabled users with their stored meal plan
# ---------------------------------------------------------------------------

def _get_reminder_users() -> list:
    """
    Return a list of dicts for every user who has reminder_enabled=True.
    Each dict contains email, name, smtp credentials, and their full
    meal_plan as stored by /diet/sync-meal-plan.
    """
    users_col = db["users"]
    reminder_users = []

    try:
        for user in users_col.find({"reminder_enabled": True}):
            email = user.get("email")
            if not email:
                continue

            reminder_users.append({
                "id":            str(user["_id"]),
                "email":         email,
                "name":          user.get("name", "there"),
                "meal_plan":     user.get("meal_plan") or {},   # keyed by lowercase day name
                "smtp_email":    user.get("smtp_email"),
                "smtp_password": user.get("smtp_password"),
            })

    except Exception as exc:
        logger.error(f"❌ Error fetching reminder users: {exc}")

    return reminder_users


# ---------------------------------------------------------------------------
# Meal lookup — reads from the stored plan, never hardcoded
# ---------------------------------------------------------------------------

def _get_meal(user: dict, meal_type: str, day_key: str) -> tuple[str | None, dict]:
    """
    Return (meal_name, nutrition_dict) for the given meal_type on day_key.
    meal_type is one of 'breakfast', 'lunch', 'dinner'.
    day_key is a lowercase day name, e.g. 'saturday'.

    Returns (None, {}) if the plan is missing or incomplete — callers should
    skip sending the email rather than sending a "Meal not set" message.
    """
    meal_plan: dict = user.get("meal_plan") or {}
    day_plan  = meal_plan.get(day_key) or {}

    meal_name = day_plan.get(meal_type) or ""
    nutrition  = day_plan.get("nutrition") or {}

    if not meal_name:
        logger.warning(
            f"⚠️  No {meal_type} found for {user['email']} on {day_key}. "
            "Skipping reminder — has sync-meal-plan been called for this user?"
        )
        return None, {}

    return meal_name, nutrition


# ---------------------------------------------------------------------------
# Email body builder
# ---------------------------------------------------------------------------

def _build_reminder_body(
    name: str,
    day_label: str,          # e.g. "Today (Saturday)" or "Tomorrow (Sunday)"
    meal_type: str,          # "Breakfast" | "Lunch" | "Dinner"
    meal_name: str,
    nutrition: dict,
) -> tuple[str, str]:
    """
    Returns (subject, plain_text_body).
    """
    emoji_map = {"Breakfast": "🍳", "Lunch": "🍛", "Dinner": "🌙"}
    emoji = emoji_map.get(meal_type, "🍽️")

    cal   = nutrition.get("calories", 0)
    prot  = nutrition.get("protein", 0)
    carbs = nutrition.get("carbohydrates", 0)
    fat   = nutrition.get("fat", 0)

    subject = f"{emoji} {day_label}'s {meal_type} Reminder — NutriAI"

    nutrition_block = ""
    if cal:
        nutrition_block = (
            f"\n📊 Nutrition:\n"
            f"   🔥 Calories : {cal} kcal\n"
            f"   💪 Protein  : {prot} g\n"
            f"   🌾 Carbs    : {carbs} g\n"
            f"   🥑 Fat      : {fat} g\n"
        )

    body = (
        f"Hello {name},\n\n"
        f"{day_label}'s {meal_type.lower()} is:\n\n"
        f"  {emoji}  {meal_name}\n"
        f"{nutrition_block}\n"
        f"Stay consistent and enjoy your meal! 💚\n"
        f"— NutriAI"
    )

    return subject, body


# ---------------------------------------------------------------------------
# Scheduled job functions
# ---------------------------------------------------------------------------

def breakfast_job():
    logger.info("🍳 Running BREAKFAST reminder job…")
    today = _today_key()
    users = _get_reminder_users()
    sent  = 0
    skipped = 0

    for user in users:
        try:
            meal_name, nutrition = _get_meal(user, "breakfast", today)
            if meal_name is None:
                skipped += 1
                continue
            subject, body = _build_reminder_body(
                name=user["name"],
                day_label=f"Today ({today.title()})",
                meal_type="Breakfast",
                meal_name=meal_name,
                nutrition=nutrition,
            )
            if send_email(
                to_email=user["email"],
                subject=subject,
                body=body,
                smtp_email=user.get("smtp_email"),
                smtp_password=user.get("smtp_password"),
            ):
                sent += 1
        except Exception as exc:
            logger.error(f"❌ Breakfast reminder failed for {user.get('email')}: {exc}")

    logger.info(f"✅ Breakfast reminders sent: {sent}/{len(users)} (skipped {skipped} — no meal plan)")


def lunch_job():
    logger.info("🍛 Running LUNCH reminder job…")
    today = _today_key()
    users = _get_reminder_users()
    sent  = 0
    skipped = 0

    for user in users:
        try:
            meal_name, nutrition = _get_meal(user, "lunch", today)
            if meal_name is None:
                skipped += 1
                continue
            subject, body = _build_reminder_body(
                name=user["name"],
                day_label=f"Today ({today.title()})",
                meal_type="Lunch",
                meal_name=meal_name,
                nutrition=nutrition,
            )
            if send_email(
                to_email=user["email"],
                subject=subject,
                body=body,
                smtp_email=user.get("smtp_email"),
                smtp_password=user.get("smtp_password"),
            ):
                sent += 1
        except Exception as exc:
            logger.error(f"❌ Lunch reminder failed for {user.get('email')}: {exc}")

    logger.info(f"✅ Lunch reminders sent: {sent}/{len(users)} (skipped {skipped} — no meal plan)")


def dinner_job():
    logger.info("🌙 Running DINNER reminder job…")
    today = _today_key()
    users = _get_reminder_users()
    sent  = 0
    skipped = 0

    for user in users:
        try:
            meal_name, nutrition = _get_meal(user, "dinner", today)
            if meal_name is None:
                skipped += 1
                continue
            subject, body = _build_reminder_body(
                name=user["name"],
                day_label=f"Today ({today.title()})",
                meal_type="Dinner",
                meal_name=meal_name,
                nutrition=nutrition,
            )
            if send_email(
                to_email=user["email"],
                subject=subject,
                body=body,
                smtp_email=user.get("smtp_email"),
                smtp_password=user.get("smtp_password"),
            ):
                sent += 1
        except Exception as exc:
            logger.error(f"❌ Dinner reminder failed for {user.get('email')}: {exc}")

    logger.info(f"✅ Dinner reminders sent: {sent}/{len(users)} (skipped {skipped} — no meal plan)")


# ---------------------------------------------------------------------------
# Immediate alert — called on profile save (send_immediate_reminder)
# ---------------------------------------------------------------------------

def send_immediate_reminder(user_id: str) -> bool:
    """
    Called when a user saves their profile.
    Determines the closest upcoming meal by local server time and sends it.
    Reads meals from users.meal_plan — the same data the dashboard shows.
    """
    logger.info(f"⚡ Sending immediate reminder for user: {user_id}")
    users_col = db["users"]

    try:
        user_doc = users_col.find_one({"_id": ObjectId(user_id)})
        if not user_doc:
            logger.warning(f"⚠️  User {user_id} not found.")
            return False

        if not user_doc.get("reminder_enabled"):
            logger.info(f"⏭️  Reminders disabled for {user_id}.")
            return False

        hour = datetime.now().hour

        # Determine which meal slot is current / upcoming:
        # 00:00–08:59  → today's Breakfast
        # 09:00–12:59  → today's Lunch
        # 13:00–18:59  → today's Dinner
        # 19:00–23:59  → tomorrow's Breakfast (today's dinner already passed at 7 PM)
        if hour < 9:
            meal_type, emoji = "Breakfast", "🍳"
            tomorrow = False
        elif hour < 13:
            meal_type, emoji = "Lunch", "🍛"
            tomorrow = False
        elif hour < 19:
            meal_type, emoji = "Dinner", "🌙"
            tomorrow = False
        else:
            # After 7 PM — dinner has passed, preview tomorrow's breakfast
            meal_type, emoji = "Breakfast", "🍳"
            tomorrow = True

        day_key = _tomorrow_key() if tomorrow else _today_key()

        user_data = {
            "email":         user_doc.get("email"),
            "name":          user_doc.get("name", "there"),
            "meal_plan":     user_doc.get("meal_plan") or {},
            "smtp_email":    user_doc.get("smtp_email"),
            "smtp_password": user_doc.get("smtp_password"),
        }

        meal_name, nutrition = _get_meal(user_data, meal_type.lower(), day_key)
        if meal_name is None:
            logger.warning(f"⚠️  No {meal_type} found for immediate reminder — user {user_id} has no meal plan yet.")
            return False
        day_label = f"Tomorrow ({day_key.title()})" if tomorrow else f"Today ({day_key.title()})"

        subject, body = _build_reminder_body(
            name=user_data["name"],
            day_label=day_label,
            meal_type=meal_type,
            meal_name=meal_name,
            nutrition=nutrition,
        )
        # Personalise subject for profile-update trigger
        subject = f"{emoji} Profile Updated — Your {day_label} {meal_type} · NutriAI"

        return send_email(
            to_email=user_data["email"],
            subject=subject,
            body=body,
            smtp_email=user_data.get("smtp_email"),
            smtp_password=user_data.get("smtp_password"),
        )

    except Exception as exc:
        logger.error(f"❌ Immediate reminder error for {user_id}: {exc}")
        return False


# ---------------------------------------------------------------------------
# Welcome email — no meal content, just onboarding
# ---------------------------------------------------------------------------

def send_welcome_email(user_id: str) -> bool:
    logger.info(f"💌 Sending welcome email for user: {user_id}")
    users_col = db["users"]
    try:
        user = users_col.find_one({"_id": ObjectId(user_id)})
        if not user:
            return False

        subject = "🌊 Welcome to NutriAI!"
        body = (
            f"Hello {user.get('name', 'there')},\n\n"
            f"Welcome to NutriAI! Your account is now active.\n\n"
            f"Complete your profile to generate a personalised 7-day meal plan. "
            f"You will then start receiving breakfast, lunch, and dinner reminders "
            f"with your exact meals from the dashboard.\n\n"
            f"Stay healthy,\n"
            f"— The NutriAI Team"
        )
        return send_email(
            to_email=user["email"],
            subject=subject,
            body=body,
            smtp_email=user.get("smtp_email"),
            smtp_password=user.get("smtp_password"),
        )
    except Exception as exc:
        logger.error(f"❌ Welcome email failed for {user_id}: {exc}")
        return False


# ---------------------------------------------------------------------------
# Scheduler setup
# ---------------------------------------------------------------------------

scheduler = BackgroundScheduler(timezone="Asia/Kolkata")


def start_scheduler():
    if scheduler.running:
        logger.warning("⚠️  Scheduler already running, skipping duplicate start.")
        return

    scheduler.add_job(breakfast_job, "cron", hour=9,  minute=0, id="breakfast_reminder", replace_existing=True)
    scheduler.add_job(lunch_job,     "cron", hour=13, minute=0, id="lunch_reminder",     replace_existing=True)
    scheduler.add_job(dinner_job,    "cron", hour=19, minute=0, id="dinner_reminder",    replace_existing=True)

    scheduler.start()
    logger.info("🚀 Meal reminder scheduler started!")
    logger.info("   ⏰ Breakfast : 09:00 AM IST")
    logger.info("   ⏰ Lunch     : 01:00 PM IST")
    logger.info("   ⏰ Dinner    : 07:00 PM IST")


def stop_scheduler():
    if scheduler.running:
        scheduler.shutdown(wait=False)
        logger.info("🛑 Meal reminder scheduler stopped.")
